### ISSUE TITLE
Enabling debug logs

### ISSUE THREAD

**Issue by cihati** [devops-infra/action-tflint#18]
One can use `TFLINT_LOG=debug tflint` to see detailed logs. How can we enable it for this GitHub action?

Thanks!

**Comment by ChristophShyper** [comment]
Have you tried adding this variable to workflow file?
Something like: 
```
      - name: Check linting of Terraform files
        uses: devops-infra/action-tflint@master
        with:
          dir_filter: submodule
        env:
          TFLINT_LOG: debug
```
